// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
)

type Todo struct {
	ID          int64
	Title       string
	Priority    sql.NullInt64
	DueDate     sql.NullTime
	IsCompleted sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type TodoDetail struct {
	ID        int64
	TodoID    int64
	Detail    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
